# Generated by Django 5.1.1 on 2024-09-25 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.IntegerField(default=0)),
                ('weight_category', models.CharField(max_length=200)),
                ('weight_code', models.CharField(max_length=30)),
                ('height', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('password2', models.CharField(max_length=255)),
                ('coach_name', models.CharField(blank=True, max_length=255, null=True)),
                ('club_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fighter_photos/')),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='fighter_id_cards/')),
                ('win', models.IntegerField(blank=True, null=True)),
                ('loss', models.IntegerField(blank=True, null=True)),
                ('no_contest', models.IntegerField(blank=True, null=True)),
                ('player_lock', models.BooleanField(default=False)),
                ('player_disqualify', models.BooleanField(default=False)),
                ('unique_id', models.CharField(editable=False, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GR grappling', 'Grappling'), ('NF normal_fighting', 'Normal Fighting'), ('BX boxing', 'Boxing')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('max_participants', models.PositiveIntegerField()),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('organizer_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_module.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_module.event')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
