# Generated by Django 5.0.6 on 2024-06-27 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GR grappling', 'Grappling'), ('NF normal_fighting', 'Normal Fighting'), ('BX boxing', 'Boxing')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('max_participants', models.PositiveIntegerField()),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('organizer_name', models.CharField(max_length=255)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_module.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_module.event')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_module.fighter')),
            ],
        ),
    ]
