# Generated by Django 5.0.6 on 2024-07-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
