# Generated by Django 5.1.1 on 2024-09-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0002_fighter_main_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='unique_id',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='weight_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='weight_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
