# Generated by Django 5.0.6 on 2024-07-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0002_alter_fighter_age_alter_fighter_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
