# Generated by Django 5.0.6 on 2024-08-14 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0002_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='club_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='fighter_id_cards/'),
        ),
        migrations.AddField(
            model_name='fighter',
            name='main_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_module.event'),
        ),
        migrations.AddField(
            model_name='fighter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fighter_photos/'),
        ),
    ]
