# Generated by Django 5.1.1 on 2024-09-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0003_alter_fighter_age_alter_fighter_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.CharField(choices=[('GR grappling', 'Grappling'), ('NF normal_fighting', 'Normal Fighting'), ('BX boxing', 'Boxing'), ('MMA', 'MMA Match')], max_length=20),
        ),
    ]
