# Generated by Django 5.0.2 on 2024-09-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0003_fighter_club_name_fighter_id_card_fighter_main_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
