# Generated by Django 5.0.2 on 2024-09-18 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0004_alter_fighter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='username',
        ),
    ]
