# Generated by Django 5.1.1 on 2024-09-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0004_alter_eventtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.CharField(choices=[('GR grappling', 'Grappling'), ('NF normal_fighting', 'Normal Fighting'), ('BX boxing', 'Boxing'), ('MMA', 'MMA Match'), ('MMA', 'MMA Strike')], max_length=20),
        ),
    ]
