# Generated by Django 5.1.1 on 2024-09-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0005_alter_eventtype_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighter',
            old_name='is_active',
            new_name='is_fighter_active',
        ),
    ]
