# Generated by Django 5.0.2 on 2024-09-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0005_remove_fighter_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fighter',
            options={},
        ),
        migrations.AlterModelManagers(
            name='fighter',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='user_permissions',
        ),
    ]
