# Generated by Django 5.0.2 on 2024-09-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0006_alter_fighter_options_alter_fighter_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='password2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
