# Generated by Django 5.1.1 on 2024-10-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0006_rename_is_active_fighter_is_fighter_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='main_event',
        ),
    ]
