# Generated by Django 5.0.2 on 2024-09-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0007_alter_fighter_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='password2',
            field=models.CharField(max_length=255),
        ),
    ]
