# Generated by Django 5.1.1 on 2024-10-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0007_remove_fighter_main_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='main_event',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
