# Generated by Django 5.1.1 on 2024-10-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0008_fighter_main_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.IntegerField()),
                ('event_name', models.CharField(max_length=255)),
                ('fighterid', models.IntegerField()),
                ('fighter_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Registration Event',
                'verbose_name_plural': 'Registration Events',
            },
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='main_event',
        ),
    ]
