# Generated by Django 5.0.2 on 2024-09-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0008_alter_fighter_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fighter',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
