# Generated by Django 5.0.2 on 2024-09-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0009_fighter_is_active_fighter_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
