# Generated by Django 5.1.1 on 2024-10-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0009_registrationevent_remove_fighter_main_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationevent',
            name='fighterid',
            field=models.CharField(max_length=255),
        ),
    ]
