# Generated by Django 5.0.2 on 2024-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0011_fighter_coach_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
