# Generated by Django 5.0.2 on 2024-09-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0012_fighter_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
