# Generated by Django 5.1.1 on 2024-09-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0013_alter_fighter_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='weight_category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
