# Generated by Django 5.1.1 on 2024-09-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0014_fighter_weight_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='loss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='no_context',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='unique_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='win',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
