# Generated by Django 5.1.1 on 2024-09-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0015_fighter_loss_fighter_no_context_fighter_unique_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighter',
            old_name='no_context',
            new_name='no_contest',
        ),
    ]
