# Generated by Django 5.1.1 on 2024-09-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0016_rename_no_context_fighter_no_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='middle_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
