# Generated by Django 5.1.1 on 2024-09-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0017_fighter_last_name_fighter_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='number',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
