# Generated by Django 5.1.1 on 2024-09-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0018_fighter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='unique_id',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
