# Generated by Django 5.1.1 on 2024-09-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0020_alter_fighter_last_name_alter_fighter_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='last_name',
            field=models.CharField(blank=True, default='N', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='middle_name',
            field=models.CharField(blank=True, default='N', max_length=255, null=True),
        ),
    ]
